#!/bin/bash
   pip install discogs-client 
    pip3 install flask pyacoustid requests
    sudo add-apt-repository ppa:robert-tari/main 
    sudo apt-get update 
    sudo apt-get install mac
    sudo wget https://raw.githubusercontent.com/ftrvxmtrx/split2flac/master/split2flac -P /usr/bin/
