- hosts: all
  tasks:  
    - name: Set locales
      vars:
          locale: en_IE.UTF-8
          parameters:
            - LANG
            - LC_ALL
            - LANGUAGE
            - LC_NUMERIC
            - LC_TIME
            - LC_MONETARY
            - LC_PAPER
            - LC_NAME
            - LC_ADDRESS
            - LC_TELEPHONE
            - LC_MEASUREMENT
            - LC_IDENTIFICATION
      block:
        - shell: >
            kwriteconfig5
            --file plasma-localerc
            --group Formats
            --key {{ item }}
            "{{ locale }}"
          loop: "{{ parameters }}"
        - replace:
            path: /home/{{ ansible_user_id }}/.config/plasma-localerc
            regexp: 'export {{ item }}=.*'
            replace: 'export {{ item }}={{ locale }}'
          loop: "{{ parameters }}"
        - replace:
            path: /etc/default/locale
            regexp: 'export {{ item }}=.*'
            replace: 'export {{ item }}={{ locale }}'
          loop: "{{ parameters }}"
        - shell: "update-locale {{ item }}={{ locale }}"
          loop: "{{ parameters }}"
          become: yes
        - community.general.locale_gen:
            name: "{{locale}}"
            state: present
          become: yes


    - name: Disable logout confirmation
      shell: >
          kwriteconfig5 
          --file ksmserverrc 
          --group General
          --key confirmLogout
          --type bool
          false

    - name: Login with empty session
      shell: >
          kwriteconfig5 
          --file ksmserverrc 
          --group General
          --key loginMode
          default
    - name: Disable Splash
      shell: >
          kwriteconfig5 
          --file ksplashrc
          --group KSplash
          --key Engine
          none

    - name: Disable Splash
      shell: >
          kwriteconfig5 
          --file ksplashrc
          --group KSplash
          --key Theme
          None

    - name: Create Wallpaper Folders if they dont exist
      block:
        - file:
            path: /home/{{ ansible_user_id }}/Wallpapers/SDDM/
            state: directory
            mode: '0755'
        - file:
            path: /home/{{ ansible_user_id }}/Wallpapers/Desktop/
            state: directory
            mode: '0755'

    - name: Set SDDM Wallpaper
      become: yes
      block:
        - replace:
            path: /usr/share/sddm/themes/ubuntu-theme/theme.conf
            regexp: background=.*
            replace: background=/home/{{ ansible_user_id }}/Wallpapers/SDDM/background.png

    - name: Configure Materia and Kvantum
      tags: rice
      block:
        - name: Add Materia repo
          become: yes
          apt_repository: 
            repo: ppa:papirus/papirus
        - name: Install Materia and Kvantum
          become: yes
          apt:
            name: "{{ packages }}"
            state: latest
            update_cache: yes
            install_recommends: yes
          vars:
            packages:
              - materia-kde 
              - qt5-style-kvantum
              - qt5-style-kvantum-themes
        - name: Link Materia theme
          file:
            src: /usr/share/Kvantum/Materia
            state: link
            dest: /home/{{ ansible_user_id }}/.config/Kvantum/Materia
            force: yes
        - name: Link Materia Dark theme
          file:
            src: /usr/share/Kvantum/MateriaDark
            state: link
            dest: /home/{{ ansible_user_id }}/.config/Kvantum/MateriaDark
            force: yes
        - name: Install Materia in Kvantum
          shell: kvantummanager --set MateriaDark

    - name: Configure Papirus Icon Pack
      block: 
        - name: Add Papirus repo
          become: yes
          apt_repository: 
            repo: ppa:papirus/papirus
        - name: Install Papirus
          become: yes
          apt:
            name: papirus-icon-theme
            state: latest
            update_cache: yes
            install_recommends: yes

    - name: Install Event Calendar
      block:
        - name: Download Event Calendar
          git:
              repo: https://github.com/Zren/plasma-applet-eventcalendar.git
              dest: /tmp/eventcalendar
              force: yes
        - name: Make installer executable
          file: 
            dest: /tmp/eventcalendar/install
            mode: a+x
        - name: Install Event Calendar
          shell: ./install
          ignore_errors: yes
          args:
            chdir: /tmp/eventcalendar

    - name: Set Screen Locker to Materia
      shell: >
          kwriteconfig5 
          --file kscreenlockerrc
          --group Greeter
          --key Theme
          com.github.varlesh.materia
    - name: Set Screen Locker Background
      shell: >
          kwriteconfig5 
          --file kscreenlockerrc
          --group Greeter
          --group Wallpaper
          --group org.kde.image
          --group General
          --key Image
          "file:///home/{{ ansible_user_id }}/Wallpapers/SDDM/background.png"
    - name: Set Icon Pack to Papirus
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group Icons
          --key Theme
          Papirus
    - name: Set Plasma Shell to Materia
      shell: >
          kwriteconfig5 
          --file plasmarc
          --group Theme
          --key name
          Materia
    - name: Set KDE Global Theme
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group General
          --key Name
          Materia Dark
    - name: Set KDE Global Theme
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group General
          --key ColorScheme
          MateriaDark
    - name: Set KDE Global Theme
      shell: >
          kwriteconfig5 
          --file kwinrc
          --group KDE
          --key ColorScheme
          MateriaDark
    - name: Set KDE Global Theme
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group KDE
          --key ColorScheme
          MateriaDark
    - name: Set KDE Global Theme
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group KDE
          --key LookAndFeelPackage
          com.github.varlesh.materia
    - name: Set KDE Color Theme
      shell: lookandfeeltool -a com.github.varlesh.materia
    - name: Set Widget Style to kvantum
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group KDE
          --key widgetStyle
          kvantum
    - name: Set Widget Style to kvantum
      shell: >
          kwriteconfig5 
          --file kdeglobals
          --group General
          --key widgetStyle
          kvantum
    - name: Link user icon
      file: 
        src: /home/{{ ansible_user_id }}/.dotfiles/icons/user_icon.png
        dest: /home/{{ ansible_user_id }}/.face.icon
        state: link
    - name: Link user icon
      file: 
        src: /home/{{ ansible_user_id }}/.dotfiles/icons/user_icon.png
        dest: /home/{{ ansible_user_id }}/.face
        state: link
        force: yes


